# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: ubuntu-16.04

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core SDK 2.2.103'
  continueOnError: false
  inputs:
    packageType: 'sdk'
    version: '2.2.103'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: build
    arguments: '--no-restore'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test